flags: {}
packages:
- '.'
extra-deps:
- HDBC-2.4.0.1
- HDBC-postgresql-2.3.2.3
- HDBC-session-0.1.0.0
- persistable-record-0.1.0.0
- relational-query-0.5.1.1
- relational-query-HDBC-0.1.0.0
- names-th-0.1.0.1
- relational-schemas-0.1.0.2
- sql-words-0.1.3.1
resolver: nightly-2015-07-11
